# Generated by Django 5.1.1 on 2024-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('Tốt', 'Tốt'), ('Hư', 'Hư')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Đang sử dụng', 'Đang sử dụng'), ('Chưa sử dụng', 'Chưa sử dụng'), ('Hư', 'Hư')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Trống', 'Trống'), ('Không trống', 'Không trống')], max_length=15, null=True),
        ),
    ]
