# Generated by Django 5.1.1 on 2024-10-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_device_condition_alter_device_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Đang sử dụng', 'Đang sử dụng'), ('Chưa sử dụng', 'Chưa sử dụng'), ('Hư', 'Hư'), ('Đang bảo trì', 'Đang bảo trì')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('status_after', models.CharField(choices=[('Bình thường', 'Bình thường'), ('Chập chờn', 'Chập chờn'), ('Hư', 'Hư')], max_length=20, null=True)),
                ('note', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.device')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.device')),
            ],
        ),
    ]
